### ISSUE TITLE
mode 1 tiling issue

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-hinet#3]
using 'HINet(clip=clip, mode=1, device_index=0, tile_x=424, tile_y=480, fp16=True)' I see green artifact
![artifacts](https://user-images.githubusercontent.com/843640/142740050-78ecd0c0-7624-492c-a008-51432fbafab1.png)
uploaded the full script and the source file to my [GoogleDrive](https://drive.google.com/drive/folders/1h2b2ch8GwfHQeQ4pHExo4_Ns2b_HozwK?usp=sharing)

Okay, correction, this does also happen when tiling is deactivated, so this seems to be a bug in mode=1.
Using `clip = HINet(clip=clip, mode=1, device_type="cpu")` does not show theses artifacts. (using cpu instead of gpu)

**Comment by HolyWu** [comment]
Hmm...both mode=0 and mode=1 have this issue. Clamping the pixel value to 0-1 range still cannot eliminate all of them. Probably the model itself doesn't do well in fp16.

**Comment by Selur** [comment]
Okay, sad to here it's a model issue since that probably won't be fixed.
So fp16 needs to be disabled when using mode=0 and mode=1 are used.
