### ISSUE TITLE
[REQ] Restormer port

### ISSUE THREAD

**Issue by AIisCool** [HolyWu/vs-hinet#4]
Hi HolyWu, thank you as always for all the hard work you do in porting these for VS. Would it be possible to port this as well?

[Restormer: Efficient Transformer for High-Resolution Image Restoration](https://github.com/swz30/Restormer)

Thank you.

**Comment by forart** [comment]
[RealBasicVSR](https://github.com/ckkelvinchan/RealBasicVSR) by @ckkelvinchan has just been released:

https://user-images.githubusercontent.com/7676947/143370499-9fe4069b-46cc-4f12-b6ff-5595e8e5e0b8.mp4

https://user-images.githubusercontent.com/7676947/143370350-91f751f3-0f33-4ee4-9b1a-b9279bf41c18.mp4

https://user-images.githubusercontent.com/7676947/143370556-9e7019d4-e718-46af-859f-54d5576cd370.mp4

https://user-images.githubusercontent.com/7676947/143370859-e0293b97-f962-476f-acf8-14fad27cea77.mp4

(videos have been compressed. Therefore, the results are inferior to that of the actual outputs)

**Comment by HolyWu** [comment]
Sorry, not interested.
